version: "3"
services:
  prod:
    image: idsa18/microblog:1.0.0-prod
    container_name: microblog-prod
    restart: always
    environment:
      - SECRET_KEY=kabuljan1
      - DATABASE_URL=mysql+pymysql://microblog:kabuljan1@dbserver/microblog
    depends_on:
      - "mysql"
    links:
      - mysql:dbserver
    ports:
      - "8000:5000"

  mysql:
    image: mysql/mysql-server:5.7
    container_name: mysql
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=microblog
      - MYSQL_USER=microblog
      - MYSQL_PASSWORD=kabuljan1

  test:
      image: idsa18/microblog:1.0.0-test
      container_name: microblog-tests
      volumes:
        - ./app:/home/microblog/app
        - ./tests:/home/microblog/tests