---
packages:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - python3-pip
    - virtualenv
    - python3-setuptools
    - gnupg

docker_Installation_pkgs:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose-plugin
