---
- name: Update apt-cache and upgrade
  apt:
    force_apt_get: yes
    update_cache: "True"
    cache_valid_time: 3600
    upgrade: yes


- name: Starting a docker container
  docker_container:
      name: "{{ container_name }}"
      image: "{{ image_name }}"
      state: started
      ports:
        - "3306:3306"
      volumes:
        - "{{ db_volume }}:/var/lib/mysql:rw"
      restart: true
      env:
        MYSQL_RANDOM_ROOT_PASSWORD: "{{ mysql_root_pass }}"
        MYSQL_DATABASE: "{{ db_name }}"
        MYSQL_USER: "{{ db_name }}"
        MYSQL_PASSWORD: "{{ mysql_root_pass }}"
